# Generated by Django 3.1 on 2020-10-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201027_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_attributes',
            name='date',
            field=models.DateTimeField(default='2020-10-27 19:34:54.781497'),
            preserve_default=False,
        ),
    ]
