# Generated by Django 3.1 on 2020-10-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_attributes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='priority',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
