# Generated by Django 3.1 on 2020-10-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201027_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.FloatField(),
        ),
    ]
