# Generated by Django 3.1 on 2020-10-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201027_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_attributes',
            name='pneumonia',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
