# Generated by Django 3.1 on 2020-10-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_attributes_pneumonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='available_beds',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_beds',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
