# Generated by Django 3.1 on 2020-10-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201027_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='fulfilled',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
