# Generated by Django 3.1 on 2020-10-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_request_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='confirmtime',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
